export const regalos = [
    { id: 1, nombre: "Una vida con propósito", tipo: "Libro" },
    { id: 2, nombre: "Una vida apasionada", tipo: "Libro" },
    { id: 3, nombre: "Ideología de género", tipo: "" },
    { id: 4, nombre: "La mentira", tipo: "Libro" },
    { id: 5, nombre: "Seis maneras de conservar al niño bueno que hay en tu hijo", tipo: "Libro" },
    { id: 6, nombre: "El poder de los abuelos que oran", tipo: "Libro" },
    { id: 7, nombre: "Desarrolle los líderes que están alrededor de usted", tipo: "Libro" },
    { id: 8, nombre: "En el ojo de la tormenta", tipo: "Libro" },
    { id: 9, nombre: "Botilito, caja de promesas", tipo: "Regalo" },
    { id: 10, nombre: "Biblia bilingüe", tipo: "Biblia" },
    { id: 11, nombre: "Cómo orar por los hijos pródigos", tipo: "Libro" },
    { id: 12, nombre: "No desperdicies tu vida", tipo: "Libro" },
    { id: 13, nombre: "Nuestro Pan Diario", tipo: "Devocional" },
    { id: 14, nombre: "La antorcha y la espada", tipo: "Libro" },
    { id: 15, nombre: "Una esposa conforme al corazón de Dios", tipo: "Libro" },
    { id: 16, nombre: "Le dije adiós a las citas amorosas", tipo: "Libro" },
    { id: 17, nombre: "Lo quiero ya", tipo: "Libro" },
    { id: 18, nombre: "Elías", tipo: "Libro" },
    { id: 19, nombre: "El nombre de Jesús", tipo: "Libro" },
    { id: 20, nombre: "Incendiario", tipo: "Libro" },
    { id: 21, nombre: "Lenguaje secreto de las parejas exitosas", tipo: "Libro" },
    { id: 22, nombre: "Convicciones más que creencias", tipo: "Libro" },
    { id: 23, nombre: "Oraciones para niños", tipo: "Devocional" },
    { id: 24, nombre: "Sueños u visiones", tipo: "Libro" },
    { id: 25, nombre: "Dé el salto", tipo: "Libro" },
    { id: 26, nombre: "Propósito para vivir", tipo: "Libro" },
    { id: 27, nombre: "La búsqueda final", tipo: "Libro" },
    { id: 28, nombre: "Ayuno del Señor", tipo: "Libro" },
    { id: 29, nombre: "Varita del amor, más llavero promesas", tipo: "Regalo" },
    { id: 30, nombre: "Biblia en orden cronológico", tipo: "Biblia" },
    { id: 31, nombre: "Un tesoro incalculable llamado familia", tipo: "Libro" },
    { id: 32, nombre: "Yo declaro", tipo: "Libro" },
    { id: 33, nombre: "Oraciones para la victoria en tu matrimonio", tipo: "Libro" },
    { id: 34, nombre: "Jesús el Cristo", tipo: "Libro" },
    { id: 35, nombre: "Bendición o maldición", tipo: "Libro" },
    { id: 36, nombre: "Lo quiero ya", tipo: "Libro" },
    { id: 37, nombre: "Cómo conducir a tus hijos a Cristo", tipo: "Libro" },
    { id: 38, nombre: "Victoria sobre la oscuridad", tipo: "Libro" },
    { id: 39, nombre: "Introducción a la Biblia", tipo: "Libro" },
    { id: 40, nombre: "Corazón pródigo", tipo: "Libro" },
    { id: 41, nombre: "El poder del esposo que ora", tipo: "Libro" },
    { id: 42, nombre: "El esplendor de la gloria sanadora", tipo: "Libro" },
    { id: 43, nombre: "Libro devocionario de Dios para chicos", tipo: "Libro" },
    { id: 44, nombre: "Esposos y padres", tipo: "Libro" },
    { id: 45, nombre: "Qué hacer cuando los adolescentes luchan con desórdenes alimenticios", tipo: "Libro" },
    { id: 46, nombre: "Los siete niveles de la bendición", tipo: "Libro" },
    { id: 47, nombre: "Cuando tu hijo sufre", tipo: "Libro" },
    { id: 48, nombre: "Bajo el abrigo", tipo: "Libro" },
    { id: 49, nombre: "Sexo, culpa y perdón", tipo: "Libro" },
    { id: 50, nombre: "Biblia de apuntes edición grande", tipo: "Biblia" },
    { id: 51, nombre: "Gente común, perdidos y hallados", tipo: "Libro" },
    { id: 52, nombre: "Bendecidos en la oscuridad", tipo: "Libro" },
    { id: 53, nombre: "Un joven conforme al corazón de Dios", tipo: "Libro" },
    { id: 54, nombre: "La persona, el lugar correcto, el plan correcto", tipo: "Libro" },
    { id: 55, nombre: "Más allá del odio", tipo: "Libro" },
    { id: 56, nombre: "Cuidado con esa boca", tipo: "Libro" },
    { id: 57, nombre: "Familias confiadas", tipo: "Libro" },
    { id: 58, nombre: "Cuadro La Mujer Sabia, más Cristomicina", tipo: "Regalo" },
    { id: 59, nombre: "¿Por qué? Por causa de la unción", tipo: "Libro" },
    { id: 60, nombre: "Agorafobia", tipo: "Libro" },
    { id: 61, nombre: "El libro que tu pastor quiere que leas", tipo: "Libro" },
    { id: 62, nombre: "Salvos sin lugar a dudas", tipo: "Libro" },
    { id: 63, nombre: "Biblia de referencia Thompson", tipo: "Biblia" },
];
